# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_lil_jstor', '0004_coloringbook_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_lil_jstor.ColoringBook')),
            ],
        ),
    ]
